version: '2.2'

services:

  web-service:
    container_name: web-service
    build:
      context: .
      network: gcloud_example_pipeline
    volumes:
      - './:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3007:3006' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=${NODE_ENV}
      - REACT_APP_USERS_SERVICE_URL=${USERS_SERVICE_URL}
      - REACT_APP_MOVIES_SERVICE_URL=${MOVIES_SERVICE_URL}
      - REACT_APP_OMDB_API_KEY=${OMDB_API_KEY}

networks:
  default:
      external:
          name: gcloud_example_pipeline
